version: '3.8'

services:
  python-app:
    devices:
      - /dev/hidraw0:/dev/hidraw0
      - /dev/hidraw1:/dev/hidraw1
      - /dev/bus/usb/001/006:/dev/bus/usb/001/006
    build: .
    container_name: python_pylsl_emotiv
    privileged: true
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - USB_DEVICE=1234:ed02
    command: ["conda", "run", "-n", "lsl_env", "python", "main.py"]
